# Generated by Django 6.0 on 2025-12-12 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок новини')),
                ('text', models.TextField(verbose_name='Текст новини')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата')),
                ('image', models.ImageField(blank=True, upload_to='news/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Новина',
                'verbose_name_plural': 'Новини',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Назва послуги')),
                ('category', models.CharField(choices=[('nails', 'Нігтьовий сервіс'), ('brows', 'Брови та Вії'), ('massage', 'Масаж'), ('cosmetology', 'Косметологія'), ('hair', 'Перукарське мистецтво')], default='nails', max_length=20, verbose_name='Категорія')),
                ('price', models.CharField(max_length=50, verbose_name='Ціна')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('image', models.ImageField(blank=True, upload_to='services/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Послуга',
                'verbose_name_plural': 'Послуги',
            },
        ),
    ]
