# Generated by Django 5.2.9 on 2025-12-17 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0002_alter_news_id_alter_service_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Ім'я клієнта")),
                ("phone", models.CharField(max_length=20, verbose_name="Телефон")),
                (
                    "message",
                    models.TextField(blank=True, verbose_name="Побажання / Послуга"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата заявки"),
                ),
            ],
            options={
                "verbose_name": "Заявка на запис",
                "verbose_name_plural": "Заявки на запис",
            },
        ),
    ]
