# Generated by Django 5.2.9 on 2025-12-17 01:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0003_appointment"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="service",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="web.service",
                verbose_name="Послуга",
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="message",
            field=models.TextField(blank=True, verbose_name="Коментар"),
        ),
    ]
